title: Workflow Docs
description: Documentation for Mitel workflow
# baseurl: "workflow-docs" # the subpath of your site, e.g. /blog
# url: "https://mitel-networks.github.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/logos/logo_corporate.png"

permalink: pretty
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

plugins:
  - jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs

footer_content: "Copyright &copy; 2017-2019 Mitel."

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

color_scheme: mitel
