title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "workflow-docs" # the subpath of your site, e.g. /blog
url: "https://mitel-networks.github.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/logo.png"

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nill

remote_theme: pmarsceill/just-the-docs
